CREATE DB

CREATE DATABASE RECETTES;

CREATE TABLES 


CREATE TABLE RECETTES(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom VARCHAR(200) NOT NULL,
type VARCHAR (20) NOT NULL,
description TEXT,
PRIMARY KEY (id)
)
ENGINE=INNODB;



CREATE TABLE INGREDIENTS(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom VARCHAR(40) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE COMMENTAIRES (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
titre VARCHAR(40) NOT NULL,
description TEXT,
type VARCHAR (20) NOT NULL,
objet_id SMALLINT NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;


CREATE TABLE RECETTES_INGREDIENTS(
ingredient_id SMALLINT NOT NULL,
recette_id SMALLINT NOT NULL,
quantité INT NOT NULL,
PRIMARY KEY (recette_id,ingredient_id)
)
ENGINE=INNODB;

CREATE TABLE PHOTO (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
recette_id SMALLINT NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

